/**
 * WKT to GeoJSON Converter (wkt2geojson.c)
 *
 * Well-Known Text (WKT) is a text markup language used to represent
 * vector geometry objects, as defined by the
 * Open Geospatial Consortium (OGC) (Wikipedia, 2024).
 *
 * GeoJSON is a standard format, based on JSON, for encoding a variety
 * of geographic data structures, including simple geographical
 * features and their non-spatial attributes (Wikipedia, 2024).
 *
 * This program is a command-line utility that converts a
 * WKT (Well-Known Text) file to a GeoJSON (Geographic JSON) file.
 * The program leverages a lexical analyzer
 * and parser to process the WKT data and produce a valid
 * GeoJSON output.
 *
 * The output GeoJSON file is valid but may not be formatted for
 * readability. To format the output in a more readable way, it can
 * be piped through a JSON beautifier tool, such as `jq` or `json_pp`.
 * For example:
 *
 *   ./wkt2geojson < input.wkt | jq . > output.geojson
 *
 * Command-Line Options:
 *
 * - `-i <file>`: Specifies the input file.
 *   If not provided, the program reads from stdin.
 * - `-o <file>`: Specifies the output file.
 *   If not provided, the program writes to stdout.
 * - `-h`: Displays the help message with usage instructions.
 *
 * **Usage Examples**:
 * ```
 * ./wkt2geojson -i input.wkt -o output.geojson
 * ./wkt2geojson < input.wkt > output.geojson
 * ```
 * This command reads WKT data from `input.wkt` and writes the
 * corresponding GeoJSON to `output.geojson`. If any of the file
 * options are omitted, the program defaults to using stdin and stdout.
 *
 * The `getopt` function is used to parse the command-line options.
 * The available options are:
 * - `i`: Specifies the input file path.
 * - `o`: Specifies the output file path.
 * - `h`: Prints the help message and exits.
 *
 * The program flow is as follows:
 * 1. Command-line arguments are processed using `getopt`.
 * 2. The input file is opened
 *   (or stdin is used if no file is provided).
 * 3. The output file is opened
 *   (or stdout is used if no file is provided).
 * 4. The parser is invoked to transpile the WKT data into GeoJSON.
 * 5. After processing, the input and output files are closed
 *   (if they were opened).
 *
 * **Error Handling**:
 * - If the input file cannot be opened, an error message is printed,
 *   and the program exits with a status of 1.
 * - If the output file cannot be opened, an error message is printed,
 *   and the program exits with a status of 1.
 *
 * **Return Value**:
 * - Returns 0 on success.
 * - Returns 1 on error.
 *
 * Dependencies:
 * - `getopt.h`: Used for parsing command-line arguments.
 * - `parser.tab.h`: Generated by Bison, contains the declarations
 *   for the parser.
 *
 * Functions:
 * - `print_help`: Displays the usage instructions.
 * - `main`: Entry point for the program. Handles argument parsing,
 *   file I/O, and invocation of the parser.
 *
 * License:
 * This project is licensed under the MIT License. See the LICENSE file
 * for more details.
 *
 */


#include <stdio.h>
#include <stdlib.h>
#include <getopt.h>

#include "parser.tab.h"

void print_help(const char *program_name) {
    printf("Usage: %s [options]\n", program_name);
    printf("Options:\n");
    printf("  -i <file>  Specify input file (default: stdin)\n");
    printf("  -o <file>  Specify output file (default: stdout)\n");
    printf("  -h         Display this help message\n");
}


int main(int argc, char *argv[]) {
    int opt;
    char *input_file = NULL;
    char *output_file = NULL;

    while ((opt = getopt(argc, argv, "i:o:h")) != -1) {
        switch (opt) {
            case 'i':
                input_file = optarg;
                break;
            case 'o':
                output_file = optarg;
                break;
            case 'h':
                print_help(argv[0]);
                return 0;
            default:
                print_help(argv[0]);
                return 1;
        }
    }

    FILE *input_fp = stdin;
    FILE *output_fp = stdout;

    if (input_file) {
        input_fp = fopen(input_file, "r");
        if (!input_fp) {
            perror("Error opening input file");
            return 1;
        }
    }

    if (output_file) {
        output_fp = fopen(output_file, "w");
        if (!output_fp) {
            perror("Error opening output file");
            fclose(input_fp);
            return 1;
        }
    }

    /** Run the parser */
    int status = 1;
    if (!transpile(input_fp, output_fp)) {
        status = 0;
    }

    // Cleanup
    if (input_fp != stdin) fclose(input_fp);
    if (output_fp != stdout) fclose(output_fp);

    return status;
}
