version: "3.3"

services:

  wkt2geojson:

    container_name: wkt2geojson
    image: wkt2geojson:latest
    restart: unless-stopped

    build: 
      context: .
      dockerfile: Dockerfile.dev

    environment:
      - APP_ROOT_DIR=/app
      - LOG_FILE=/var/log/wkt2geojson/wkt2geojson.log

    volumes:      
      - .:/app
