FROM debian:latest

RUN apt update -y && export DEBIAN_FRONTEND=noninteractive && apt install -y \
    build-essential \
    flex \
    bison \
    valgrind \
    && rm -Rf /var/lib/apt/lists/*

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["/app/scripts/container/start_app.csh"]
