FROM debian:latest

RUN apt update -y && export DEBIAN_FRONTEND=noninteractive && apt install -y \
    build-essential \
    vim \
    flex \
    bison \
    valgrind \
    jq \
    && rm -Rf /var/lib/apt/lists/*

ENTRYPOINT ["/app/scripts/docker-entrypoint.sh"]
CMD ["/app/scripts/start_app.sh"]
